name: CI
run-name: "CI: ${{ github.event.head_commit.message }}"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - name: Lint
        run: npx nx run-many -t lint

      - name: Test
        run: npx nx run-many -t test

      - name: Build Angular library
        run: npx nx run angular:build

      - name: Build docs app
        run: npx nx run docs:build
